# Generated by Django 5.1 on 2024-08-23 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMentor',
            fields=[
                ('studmenid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('mentcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.mentor')),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
    ]
